config/routes.rb
Rails.application.routes.draw do
  get 'monthly_figures/index'
  get 'import_responses/create'
  get 'import_responses/destroy'
  root "imports#index"

  resources :imports do
    resources :rawrecruitments
    resources :daily_figures
  end

  resources :result_matrices, only: [:index]
  resources :monthly_figures, only: [:index]
end

app/models/import.rb
class Import < ApplicationRecord
  has_many :raw_recruitments, dependent: :destroy
  has_many :daily_figures, dependent: :destroy
  has_many :responses

  #
  # r01Completers = RawRecruitment.select(:Day, :id).where(dispcode:'Invited (12)').or(RawRecruitment.select(:Day,:id).where(dispcode:'E-mail could not be delivered (14)')).group(:Day).count(:id)
  # r02Starters = RawRecruitment.select(:Day, :id).where(dispcode:'Suspended (22)').or(RawRecruitment.select(:Day,:id).where(dispcode: 'Screened out (37)')).group(:Day).count(:id)
  # recruited = RawRecruitment.select(:Day, :id).where(dispcode:'Completed (31)').or(RawRecruitment.select(:Day,:id).where(dispcode: 'Custom completed 1 (33)')).group(:Day).count(:id)
  #
  #
  # def r01_Completers_To_Recruited_Ratio
  #   # r01Completers = RawRecruitment.select(:Day, :id).where(dispcode:'Invited (12)').or(RawRecruitment.select(:Day,:id).where(dispcode:'E-mail could not be delivered (14)')).group(:Day).count(:id)
  #   RawRecruitment.find_by_sql("SELECT day, COUNT(id) FROM raw_recruitments WHERE import_id IS #{self.id} AND dispcode IS 'Invited (12)' OR dispcode IS 'E-mail could not be delivered (14)' GROUP BY day;")
  #   ratio = recruited / r01Completers * 100
  #   ratio.round(half: :up)
  # end
  #
  # def r02_Starters_To_Recruited_Ratio
  #   ratio = recruited / r02Starters * 100
  #   ratio.round(half: :up)
  # end
  #
  # def r01_Completes_To_R02_Starters_Ratio
  #   ratio = recruited / r02Starters * 100
  #   ratio.round(half: :up)
  # end


end

app/controllers/imports_controller.rb
require "roo"
require "time"
require "pry"

class ImportsController < ApplicationController
  def create
    upload_file = params[:import][:file]
    upload_filename = upload_file.original_filename
    upload_path = Rails.root.join("public", "uploads", upload_filename)

    File.open(upload_path, "wb") do |file|
      file.write(upload_file.read)
    end

    @import = Import.create({
                                filename: upload_filename,
                                catagory: params[:import][:catagory],
                                month: params[:import][:month],
                                processedraw: 0,
                                processed: 0,
                            })

    Roo::Excelx.new(upload_path).each_row_streaming(offset: 1) do |row|
      begin

        raw_recruitment = {
            dispcode: row[0].value.to_s,
            u_email: row[1].value.to_s,
            pstatu_date: row[2].value.to_s,
            penter: Time.parse(row[3].value.to_s).to_s,
            day: Time.parse(row[3].value.to_s).day,
            reg_code: row[4].value,
            m_recruit: row[5].value.to_s,
            m_signup: row[6].value.to_s,
            m_panel_membership: row[7].value.to_s,
            m_gender_expanded: row[8].value.to_s,
            m_age_bands_report: row[9].value.to_s,
            datetime: row[10].value.to_s
        }
        puts(raw_recruitment)
        @import.raw_recruitments.create(raw_recruitment)

      rescue StandardError => e
        puts "ERROR ----- #{e.message}"
          # binding.pry
      end
    end

    @import.update({processedraw: 1})

    create_daily_figures(@import.id)

    redirect_to imports_path
  end

  def show
    @import = Import.find(params[:id])
  end

  def index
    @import = Import.new
    @imports = Import.all
  end

  def destroy
    Import.destroy(params[:id])
    redirect_to imports_path
  end

  private

  def create_daily_figures(import_id)

    quarters = {
        "01" => "1",
        "02" => "1",
        "03" => "1",
        "04" => "2",
        "05" => "2",
        "06" => "2",
        "07" => "3",
        "08" => "3",
        "09" => "3",
        "10" => "4",
        "11" => "4",
        "12" => "4"
    }
    year, month = params[:import][:month].split("-")

    quarter = [year, quarters[month]].join("")

    raw_r01 = RawRecruitment.select(:day, :dispcode).where(["import_id = ?", import_id]).group(:day).count(:dispcode)
    raw_r02 = RawRecruitment.select(:day, :pstatu_date).where(["import_id = ? AND pstatu_date != 'NULL'", import_id]).group(:day).count(:pstatu_date)
    raw_recruited = RawRecruitment.select(:day, :datetime).where(["import_id = ? AND datetime != 'NULL'", import_id]).group(:day).count(:datetime)

    format_raw(year,month,raw_r01, raw_r02, raw_recruited).each do |timestamp, data|
      r01_Completers, r02_Starters, recruited = data
      r01_Completes_To_R02_Starters_Ratio = ratio(r02_Starters,r01_Completers)
      r02_Starters_To_Recruited_Ratio =  ratio(recruited,r02_Starters)
      r01_Completers_To_Recruited_Ratio = ratio(recruited,r01_Completers)


      daily_figure = {

          :R01_Completers => r01_Completers,
          :R02_Starters => r02_Starters,
          :Recruited => recruited,
          :R01_Completes_To_R02_Starters_Ratio => r01_Completes_To_R02_Starters_Ratio.round(half: :up),
          :R02_Starters_To_Recruited_Ratio => r02_Starters_To_Recruited_Ratio.round(half: :up),
          :R01_Completers_To_Recruited_Ratio => r01_Completers_To_Recruited_Ratio.round(half: :up),
          :quarter => quarter,
          :timestamp => timestamp

      }

      @import.daily_figures.create(daily_figure)
    end
  end



  def format_raw(year, month, raw_r01, raw_r02, raw_recruited)
    raw_r01.default = 0
    raw_r02.default = 0
    raw_recruited.default = 0

    last_day = (Time.new(year, month.to_i + 1) - 1).day

    data = (1..last_day).to_a.reduce(Hash.new) {|hash, day|
      hash[Time.new(year, month, day).strftime("%F")] = [
        raw_r01[day],
        raw_r02[day],
        raw_recruited[day]

      ]

      hash
    }



  end











  def ratio(val1, val2)
    if val1.nonzero?.nil? || val2.nonzero?.nil?
      return 0
    end
    val3 = val1.to_f / val2.to_f
    val3 * 100

  end

end

app/helpers/imports_helper.rb
module ImportsHelper
end

app/views/imports/index.html.erb
<%= link_to 'Results Matrix', result_matrices_path %>
<br>
<%= link_to 'Monthly/Quarterly Figures', monthly_figures_index_path %>
<section class="imports ph1 pv2">
    <%["recruitments"].each do |catagory|%>
        <section class="ba b--gray flex flex-column justify-end mh1">
            <header class="pa2">
                <h1 class="mv0 pv2 tc bb b--gray"><%=catagory.capitalize%></h1>
            </header>
            <main class="pa2 flex-auto">
                <%@imports.filter{|i| i.catagory == catagory}.each do |import|%>
                    <article class="flex items-center justify-between pa2 br2 bg-near-white ma1">
                        <div><%=link_to "#{import.filename} (#{import.raw_recruitments.count} rows)", import_path(import.id)%></div>
                        <div><%=link_to "delete", import_path(import), method: :delete%></div>
                    </article>
                <%end%>
            </main>
            <footer class="pa2">
                <%=form_with model: @import, local: true, multipart: true, class: "flex flex-column" do |f| %>
                    <%=f.text_field :catagory, type: :hidden, value: catagory %>
                    <%=f.text_field :month, pattern: /dddd-dd/, placeholder: "YYYY-MM", class: "pa2"%>
                    <%=f.file_field :file, required: true, class: "bg-gray pa2 b--transparent white"%>
                    <%=f.submit value: "Upload to #{catagory.capitalize}", class: "w-100 pa2 b--transparent bg-near-black white"%>
                <%end%>
            </footer>
        </section>
    <%end%>
</section>

app/views/imports/show.html.erb
<section class="pa4">
    <header class="flex justify-between items-center">
        <h1>Recruitments</h1>
        <h1><%=link_to "Back to imports", imports_path, class: "link"%></h1>

        <h2><%=link_to "Processed Daily Figures for this month",class: "link"%></h2>
    </header>
    <ul class="list pl0 w-100">
        <li class="row-recruitment b white ma0">
            <div>dispcode</div>
            <div>u_email</div>
            <div>pstatu_date</div>
            <div>penter_date</div>
            <div>Day</div>
            <div>reg_code</div>
            <div>m_recruit</div>
            <div>m_signup</div>
            <div>m_panel_membership</div>
            <div>m_gender_expanded</div>
            <div>m_age_bands_report</div>
            <div>datetime</div>
        </li>
        <%@import.raw_recruitments.each do |row|%>
            <li class="row-recruitment ma0">
                <div><%=row.dispcode%></div>
                <div><%=row.u_email%></div>
                <div><%=row.pstatu_date%></div>
                <div><%=row.penter%></div>
                <div><%=row.day%></div>
                <div><%=row.reg_code%></div>
                <div><%=row.m_recruit%></div>
                <div><%=row.m_signup%></div>
                <div><%=row.m_panel_membership%></div>
                <div><%=row.m_gender_expanded%></div>
                <div><%=row.m_age_bands_report%></div>
                <div><%=row.datetime%></div>
            </li>
        <%end%>
    </ul>
</section>